module.exports = [
  {
    id: 'emily',
    title: 'Emily in Paris',
    runtime: 'Clip · 3m',
    genre: 'Comedy',
    maturity: 'TV-MA',
    year: 2020,
    vibes: ['Comfort', 'Comedy', 'Feel-good', 'New this week'],
    art: 'art-emily',
    poster: '/media/posters/emily.webp',
    video: '/media/clips/emily.mp4',
  },
  {
    id: 'bridgerton',
    title: 'Bridgerton',
    runtime: 'Clip · 3m',
    genre: 'Romance',
    maturity: 'TV-MA',
    year: 2020,
    vibes: ['Comfort', 'Romance', 'Drama', 'Feel-good'],
    art: 'art-bridgerton',
    poster: '/media/posters/bridgerton.jpg',
    video: '/media/clips/bridgerton.mp4',
  },
  {
    id: 'raazi',
    title: 'Raazi',
    runtime: 'Clip · 2m',
    genre: 'Spy',
    maturity: 'U/A 13+',
    year: 2018,
    vibes: ['Thrills', 'Action', 'Drama'],
    art: 'art-raazi',
    poster: '/media/posters/raazi.jpg',
    video: '/media/clips/raazi.mp4',
  },
  {
    id: 'voicemails',
    title: 'Voicemails for Isabelle',
    runtime: 'Clip · ending',
    genre: 'Drama',
    maturity: 'U/A 16+',
    year: 2024,
    vibes: ['Comfort', 'Drama', 'Romance', 'New this week'],
    art: 'art-voicemails',
    poster: '/media/posters/voicemails.png',
    video: '/media/clips/voicemails.mp4',
  },
];
