module.exports = [
  {
    id: 'enola',
    title: 'Enola Holmes',
    runtime: 'Clip · 3m',
    genre: 'Mystery',
    maturity: 'PG-13',
    year: 2020,
    vibes: ['Comfort', 'Thrills', 'Drama', 'Feel-good'],
    art: 'art-enola',
    poster: '/media/posters/enola.jpg',
    video: '/media/clips/enola.mp4',
  },
  {
    id: 'maybe',
    title: 'Always Be My Maybe',
    runtime: 'Clip · 3m',
    genre: 'Romance',
    maturity: 'PG-13',
    year: 2019,
    vibes: ['Comfort', 'Romance', 'Comedy', 'Feel-good'],
    art: 'art-maybe',
    poster: '/media/posters/maybe.jpg',
    video: '/media/clips/maybe.mp4',
  },
  {
    id: 'raazi',
    title: 'Raazi',
    runtime: 'Clip · 2m',
    genre: 'Spy',
    maturity: 'U/A 13+',
    year: 2018,
    vibes: ['Thrills', 'Action', 'Drama'],
    art: 'art-raazi',
    poster: '/media/posters/raazi.jpg',
    video: '/media/clips/raazi.mp4',
  },
  {
    id: 'adam',
    title: 'The Adam Project',
    runtime: 'Clip · 4m',
    genre: 'Sci-fi',
    maturity: 'PG-13',
    year: 2022,
    vibes: ['Comedy', 'Action', 'Feel-good', 'New this week'],
    art: 'art-adam',
    poster: '/media/posters/adam.jpg',
    video: '/media/clips/adam.mp4',
  },
  {
    id: 'rednotice',
    title: 'Red Notice',
    runtime: 'Clip · 4m',
    genre: 'Action',
    maturity: 'PG-13',
    year: 2021,
    vibes: ['Thrills', 'Action', 'Comedy'],
    art: 'art-rednotice',
    poster: '/media/posters/rednotice.jpg',
    video: '/media/clips/rednotice.mp4',
  },
  {
    id: 'voicemails',
    title: 'Voicemails for Isabelle',
    runtime: 'Clip · ending',
    genre: 'Drama',
    maturity: 'U/A 16+',
    year: 2024,
    vibes: ['Comfort', 'Drama', 'Romance', 'New this week'],
    art: 'art-voicemails',
    poster: '/media/posters/voicemails.png',
    video: '/media/clips/voicemails.mp4',
  },
];
